### ISSUE TITLE
From research to policy

### ISSUE THREAD

**Issue by renai33** [BIDS-collaborative/cega-trace#5]
Found good articles about using evidence from impact evaluations to inform development policy at http://www.tandfonline.com/doi/abs/10.1080/19439342.2012.716857?src=recsys 
Can we get access to Taylor & Francis Online?

**Comment by tmadon** [comment]
Free online version of the PDF is here: http://www.povertyactionlab.org/publication/research-policy

**Comment by davclark** [comment]
To be clear - we have access to T&F Online but not this journal via our library.
