### ISSUE TITLE
Set up Google Drive Account

### ISSUE THREAD

**Issue by manjiangjie** [BIDS-collaborative/cega-trace#6]
Hi Everyone,

I have already set up Google Drive account as our database for now. If you received an invitation email, open the shared folder and you can add it to your own Google Drive account so that we can share data and documents together. 

Here's the link: https://drive.google.com/open?id=0B9tHcQuMozKuaWFtQ3BKbHBEZzA

**Comment by nwingin** [comment]
Can I get the invitation email too and participate? My email is nwingin@berkeley.edu 
Thank you!
