### ISSUE TITLE
Note for Short Meeting (Oct. 16th)

### ISSUE THREAD

**Issue by YangZhou0417** [BIDS-collaborative/cega-trace#7]
Hi every one!
Since we have discussed last week about still taking some time to meet while Temina is out of town, me and some teammates actually had a short meeting today and we have made some notes:

journal & Report searching:

```
* search key words: cash transfer + Unconditional Transfer + Conditional cash transfer
* Looking for journals & reports have items include "abstract" "Key word" "reference" "Published date" (better after 2010) 
* form: html&txt & pdf(html and txt will save a lot of effort!!)
* where to find:  "search contents" in in meeting note1 and google scholar
* any one who find a good resource, don't forget to create a new issue and share!
```

 *Any one who find a good journal or report, don forget to share it on our google drive! Jack has already create some files for the convenience to distribute the materials. 
Some questions for Dav:
1.Given that most of the material we find might in pdf form and in order to scrap the certain contents including  the writer's name, published date, paper name in the reference part of the material, we might need help from you to give us some help on how to do that.
2. Is there any ways that we can make our final research outcomes become a more visualization? (e.g. some techniques enable us to build a network plot about the connection of citations between the Journals & Reports we find)

**Comment by davclark** [comment]
Also please let me know once you have some samples to do text analysis on!
